### ISSUE TITLE
Emacs lua-mode default install

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#10]
Is there an easy way to make Emacs `lua-mode` available on all machines by default?

This would be convenient for people who want to hack Snabb Switch using Emacs and don't have a solution for taking their package installations around with them.

**Comment by domenkozar** [comment]
Sure we can! We have lots of Emacs packages so I just need to figure out how to use them and enable lua-mode.

**Comment by domenkozar** [comment]
@lukego deployed, let me know if it works correctly

**Comment by lukego** [comment]
Works! Thanks!
