### ISSUE TITLE
Disable IOMMU in grub

### ISSUE THREAD

**Issue by capr** [snabblab/snabblab-nixos#11]
Snabb's Intel NIC driver doesn't work well with kernel's IOMMU support, so we need to disable that in the kernel. Can you @domenkozar please show us how? :) I need that for lugano-2 but I think the solution to this is in nixops somewhere. Thanks.

**Comment by lukego** [comment]
Generally it would be handy to know how to make temporary changes to the NixOS config on a machine for the purposes of testing. Then when stuff works and is worth keeping we could PR it to the master branch here for review/merge.
