### ISSUE TITLE
Get test cases running "natively" and "out of the box" on lab servers

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#13]
I would like to be able to run our various functional and performance test suites "natively" and "out of the box" on any lab server.

For example, we should be able to run all of the CI benchmarks by running:

```
git clone https://github.com/SnabbCo/snabbswitch
cd snabbswitch
make -j
cd src
sudo make benchmarks
```

By "natively" I mean running with the host software installed by NixOS rather than depending on a docker container. The immediate challenges seem to be "hashbangs" in our scripts (addressed in snabbco/snabbswitch#737) and needing to have various software dependencies available: `bc`, `numactl`, `which`, `qemu`, etc.

I think that we may also need to package up a couple of virtual machine image files, @eugeneia is the person who knows about that. Just now I see this error message when trying to set it up manually:

```
cp: cannot stat ‘/root/.test_env/qemu-dpdk.img’: No such file or directory
```

By "out of the box" I mean that we should have per-machine sensible defaults for all of the environment variables that the test scripts depend on, particularly PCI addresses of the devices that should be used for test (`SNABB_PCI_INTEL0`, etc).

I am imagining that the simplest way to do this would be to update the global configurations of the machines to have the necessary software installed in the default environment and to define the environment variables in a suitable way. @domenkozar does that sound right?

The environment variables that I believe would suit all `lugano` servers for now are:

```
export SNABB_PCI_INTEL0=0000:01:00.0
export SNABB_PCI_INTEL1=0000:01:00.1
export SNABB_PCI0=0000:01:00.0 
```

and for other servers we would need to identify a suitable pair of ports e.g. running this command and choosing the first pair of addresses that are printed:

```
[luke@lugano-1:~/git/snabbswitch/src]$ lspci | grep 82599
01:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
01:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
```

**Comment by lukego** [comment]
I see that Max has documented the process for running tests directly on the host here: https://github.com/SnabbCo/snabbswitch/blob/master/src/doc/testing.md#running-the-test-suite-directly-on-the-host

**Comment by domenkozar** [comment]
I'll take this over as soon as I'm done with OpenStack. If it has higher priority, let me know :)

**Comment by lukego** [comment]
Thanks! I'm just appending to the wish list here :)

**Comment by domenkozar** [comment]
Fixed in https://github.com/snabblab/snabblab-nixos/commit/49ee184dcbf42679b26977b8ee7b6d6e43b441fa.

Note: this should be working once:

- https://github.com/SnabbCo/snabbswitch/pull/791 is merged 
- https://github.com/SnabbCo/snabbswitch/issues/776 is released (with above fix)

**Comment by domenkozar** [comment]
Deployed to lab servers.

**Comment by domenkozar** [comment]
Ah this closed due to the commit. Reopening until it's verified.

**Comment by domenkozar** [comment]
@lukego this is now finally deployed to all lugano servers.

Note: test fixtures are still used as built by Docker, Nix based ones need jumboping and iperf failures to be fixed. Also I need to get dpdk working, which is what I'll get on next.

**Comment by domenkozar** [comment]
This is now implemented for lugano servers, following bash environment variables are configured:

```
SNABB_PCI0=0000:01:00.0
SNABB_TEST_FIXTURES=/var/lib/snabb-test-fixtures/
SNABB_PCI_INTEL0=0000:01:00.0
SNABB_PCI_INTEL1=0000:01:00.1
SNABB_KERNEL_PARAMS=init=/nix/var/nix/profiles/system/init
```
Let's open a new issue if there's a problem running Snabb tests/benchmarks on lugano.

Note that I've fixed yesterday ability to run packetblaster benchmark.
