### ISSUE TITLE
Command not found behavior

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#14]
On the Lugano servers if I run a command that is not installed I don't seem to get the helpful message telling me which `nix-env` command I should run to get it.

For example:

```
[luke@lugano-1:~/git/snabbswitch/src]$ killall
killall: command not found
```

Perhaps a setting is needed to enable this? (Or I may be misunderstanding how it is supposed to work.)

**Comment by domenkozar** [comment]
Upstream: https://github.com/NixOS/nixpkgs/issues/12044

**Comment by lukego** [comment]
So how do we get command-not-found working on the lab servers? Sounds like we need to update our nixops deployment workflow to include a `nix-channel --update` as root?

**Comment by domenkozar** [comment]
Yes, but that's not ideal since it's imperative. We're using declarative nix channels at https://github.com/snabblab/snabblab-nixos/blob/master/modules/lab-configuration.nix#L18 I'll see if that will work together.

**Comment by domenkozar** [comment]
This is blocked by upstream: https://github.com/NixOS/nixos-channel-scripts/issues/4

**Comment by domenkozar** [comment]
This is now fixed upsteam and also on snabblab.
