### ISSUE TITLE
Mount /hugetlbfs

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#15]
Some of our test scripts expect that `/hugetlbfs` will be a mounted hugetlbfs file system where QEMU can create a file-backing for VM memory. Could be a good idea to make this standard on lab servers?

I did this manually/temporarily on `lugano-1` just now like this:

```
$ sudo mkdir /hugetlbfs
$ sudo mount -t hugetlbfs none /hugetlbfs
```

This is a dependency of #13.

**Comment by domenkozar** [comment]
@lukego let me know when you're done with experiments on lugano-1. How big do you want the hugepages to be?

**Comment by lukego** [comment]
Done with experiments, go crazy. 2MB page size (usually default) is good
