### ISSUE TITLE
Make 'lock' command available

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#20]
Feature request: Make the `lock` command from SnabbCo/snabbswitch#773 globally available on all lab servers. This command depends in the file `/var/lock/lab` to exist and be world-writable.

The script could perhaps be imported into this repository in some suitable way.

**Comment by domenkozar** [comment]
Deployed:

```
[domenkozar@lugano-3:~]$ sudo lock ls
locking /var/lock/lab.. flock: getting lock took 0.000002 seconds
snabb-openstack-testing  snabbswitch
```

**Comment by domenkozar** [comment]
Closing, this is working great.
