### ISSUE TITLE
modprobe and msr module

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#23]
More wishlist :-)

Can we have the `msr` kernel module always available on lab servers? Snabb accesses this when enabling certain profiling features.

also: can we generally install more software in the global environment so that when people try to use a common command they will find it already installed? Are there some Nix expressions for "the usual stuff that people want" that we could import for example? In this case I find myself looking for how to install `modprobe` and it would really save me time if it were already there.

**Comment by lukego** [comment]
@domenkozar I marked this one as "bug" now because I think it will block people from doing some work (see snabbco/snabbswitch#808 and snabbco/snabbswitch#809). So it would make sense to treat this as higher prio than the straight wishlist items.

Could be that this kind of change is something people like me should make ourselves or do you think it is better to ask for help on them for now?

**Comment by domenkozar** [comment]
I've pushed a fix to lab servers (https://github.com/snabblab/snabblab-nixos/commit/b561ae717e516adbe7349b455c11e9489a6d44e9), it will be active on next reboot (are you running some experiments)?

There aren't any Nix expressions for commonly needed stuff, but I think we should put together a small howto for such trivial things. I do see `modprobe` is available on lab servers, how did you install it?

**Comment by lukego** [comment]
> it will be active on next reboot (are you running some experiments)?

I think we need a protocol for when it is okay to reboot a lab server.

First idea would be to make the `lock` script available and then use `lock reboot` i.e. reboot as soon as the current test ends. In the future we could refine that e.g. to detect when the lock has been free for some idle period like 15 minutes.

Second idea would be to print a MOTD message at login to say please reboot to make new kernel settings take effect? This could be simpler/better.

**Comment by lukego** [comment]
(Rebooting all lab servers at the same time might be worth avoiding. For example if we would remove the blacklist of the Intel `i40e` driver and push that then I think all of the `lugano` servers would hang during boot. Can be better to do this in stages somehow e.g. let the users of the machine decide when.)

**Comment by domenkozar** [comment]
So in general it's better to just wait on next reboot. If there's a critical vulnerability or other issue needed of immediate reboot I'll communicate on #lab a few hours before.

**Comment by domenkozar** [comment]
Just a side note: it's indeed better to brick one machine than all of them since using ipmiview is painful and slow.

**Comment by domenkozar** [comment]
So far I've been rebooting servers by asking active users if that's ok and inspecting if any of the processes are doing something. Closing this one as `msr` has been long added to our modules :)
