### ISSUE TITLE
Warning from nix-env

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#24]
I am seeing this warning when I run `nix-env` on a lab server:

```
downloading ‘https://nixos.org/releases/nixos/unstable/nixos-16.03pre75426.2d681fd/nixexprs.tar.xz’... [0/0 KiB, 0.0 KiB/s]
warning: unable to download ‘https://nixos.org/releases/nixos/unstable/nixos-16.03pre75426.2d681fd/nixexprs.tar.xz’: HTTP response code said error (22); using cached result
```

Looks like something we need to resolve somehow?

**Comment by domenkozar** [comment]
It's a bug in Nix: https://github.com/NixOS/nix/issues/792

It should only try to download the expressions when it needs them (on deploy), not every Nix operation.

Hopefully this will be fixed soon, as I like declarative way of specifying the channel as we do now at https://github.com/snabblab/snabblab-nixos/blob/master/modules/common.nix#L20

**Comment by domenkozar** [comment]
This has been fixed now, but it may appear again. Channel updates are recycled, so they do disappear eventually, hence the HTTP error. We can keep this open until it's addressed upstream.

**Comment by domenkozar** [comment]
The bug upstream is now fixed, once tests pass I'll upgrade Nix to unstable version and this shouldn't appear again unless nixos.org is down.

**Comment by domenkozar** [comment]
We're using now always the latest stable branch, so this shouldn't happen anymore.

```
$ echo $NIX_PATH
nixpkgs=http://nixos.org/channels/nixos-16.03/nixexprs.tar.xz
```

Before we used a specific pinned version, but those are recycled through time.
