### ISSUE TITLE
Running performance experiments with Hydra

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#29]
Suppose you wanted to execute a performance experiment like SnabbCo/snabbswitch#778 using Hydra. How would you do it?

Imagine a simple test where you have two software versions, `old` and `new`, and you want to measure each one three times and compare the results.

One way to break this down into a tree of dependent Nix derivations would be like this:

```
report <-- csv <--+-- old-1
                  +-- old-2
                  +-- old-3
                  +-- new-1
                  +-- new-2
                  +-- new-3
```

The derivations `old-n` each measure the performance of the old sofware version once and logs the results in the nix store. These test runs are all executed in exactly the same way, the reason there are three is to see how consistent the results are between runs. The `new-n` derivations are the same but they test a different software version.

The `csv` derivation reads the logs from the individual test runs and summarizes the results in a CSV file.

The `report` derivation runs an R (or Rmarkdown) script to produce a high-level analysis based on the CSV data. This can then be published as a Hydra build product in some suitable format e.g. HTML.

@domenkozar what do you think?

The "cute" part here is to have one derivation per execution of a test case. This should allow Hydra to execute them all in parallel, neatly capture all the results of each individual test, and even let test runs build on each other. If three runs are not enough then we could update the `csv` derivation to depend on more results and then the existing ones could be reused while the missing ones are built on demand.

cc @kbara @eugeneia

**Comment by lukego** [comment]
Further seemingly nice properties:

- You could define multiple `report` derivations that each use the same CSV data to do different things.
- You could define multiple `csv` derivations that include different information e.g. if you need to extra another column of information from the log files.

These could easily refer to the existing test results to access their log files in the nix store and wouldn't need to actually rerun any tests.

**Comment by domenkozar** [comment]
Most trivial attempt without any abstractions:

```nix

let
  snabbswitch = pkgs.callPackage ./snabbswitch.nix {};
  oldSrc = pkgs.fetchFromGitHub { ... };
  newSrc = pkgs.fetchFromGitHub { ... };
  perfSet =  {
    new-1 = snabbswitch.override { src = newSrc; name = "snabb-new1" };
    new-2 = snabbswitch.override { src = newSrc; name = "snabb-new2" };
    new-3 = snabbswitch.override { src = newSrc; name = "snabb-new3" };
    old-1 = snabbswitch.override { src = oldSrc; name = "snabb-old1" };
    old-2 = snabbswitch.override { src = oldSrc; name = "snabb-old2" };
    old-3 = snabbswitch.override { src = oldSrc; name = "snabb-old3" };
  };
in {
  report = pkgs.stdenv.mkDerivation {
    name = "report";

    buildInputs = [ lib.attrValues perfSet ];

    buildPhase = ''
       for f in $nativeBuildInputs; do
          echo $f/output.csv
       done
    '';
  };
}
```

Where `./snabbswitch.nix` would output CSV into `$out/output.csv` and `report` would in this case also do the job of `csv`.

Note: this is just a braindump, this probably needs some a few iterations to get right. If you give me instructions how to run performance tests and how to gather results I can try to make it work :)

**Comment by lukego** [comment]
@domenkozar Cool! Seems like my mental model of Nix is not too far from reality at the moment :).

Simplest performance test you can run is probably:
```
make
sudo src/snabb snabbmark basic1 100e6
```

More satisfying but depending on #13 is:
```
make
make -C src benchmarks
```

**Comment by domenkozar** [comment]
I'm going start the work on a prototype for these benchmarks.

**Comment by domenkozar** [comment]
This can now be observed at https://hydra.snabb.co/jobset/snabbswitch/performance-testing using the following Nix expression https://gist.github.com/36b6883e4b63f1040cc1f003c9a04cf1.git

Currently it's running a simple benchmark against `master` and `next` branches of snabb. then it collects logs into one file.

**Comment by domenkozar** [comment]
Further work will be done in https://github.com/snabblab/snabblab-nixos/tree/benchmark-helpers
