### ISSUE TITLE
Git bash completion plxz

### ISSUE THREAD

**Issue by plajjan** [snabblab/snabblab-nixos#32]
I'd like to have bash completion, preferably for "all" applications but at the very least for git. I'm used to the way it works on a Ubuntu machine where you get lots of completion out of the box.

**Comment by domenkozar** [comment]
Just for reference, upstream commit that got later reverted: https://github.com/NixOS/nixpkgs/commit/ee8e15fe76a235ae3583d4e8cb4bb370f28c5eae

**Comment by domenkozar** [comment]
Deployed to all lab servers, could you confirm it fixes the issue?

**Comment by plajjan** [comment]
Yupp, seems to work, thanks :)
