### ISSUE TITLE
Allow `sudo` in builds using impure dependencies, but still using chroot

### ISSUE THREAD

**Issue by domenkozar** [snabblab/snabblab-nixos#33]
1. Set `allowed-impure-host-deps` to include sudo.
2. Set `__impureHostDeps` on mkDerivation and point to sudo.

**Comment by domenkozar** [comment]
It's going to be tricky to specify full path to sudo executable, but I'll see how this goes.

**Comment by domenkozar** [comment]
Under some edge cases, `tmux` sessions stays open after `nfv` test is ran, meaning qemu instances are still running and locking the pci devices. This causes further test runs to fail. Another reason to research this option.

**Comment by domenkozar** [comment]
Found a way to do this!

```
      nix.chrootDirs = [
        "/var/setuid-wrappers" 
        "${pkgs.sudo}"
        "${config.system.path}" 
        "/etc/sudoers" 
        "/etc/passwd" 
        "/etc/pam.d/sudo" 
        "/etc/static/pam.d/sudo" 
        (toString (pkgs.writeText "sudo.pam" config.security.pam.services.sudo.text))
       ];
```

Will test tomorrow with snabb

**Comment by lukego** [comment]
Cool!

Relatedly: Could we run tests inside a disposable [network namespace](http://man7.org/linux/man-pages/man8/ip-netns.8.html) too? This would seem to allow test cases to freely do things like create `tap` devices and setup routes and so on without affecting the host. i.e. to make the chroot act a little more like a container.

**Comment by domenkozar** [comment]
I've managed to run benchmarks successfully in chroot! This is very exciting since we'll be more deterministic (well, hardware locking is impure, but nothing we can do about it).

At least some resource leaking will be gone. I'll push the commit to `benchmark-helpers`.

For network namespaces we'd have to submit a patch for upstream. All chroot magic happens in https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L1837
