### ISSUE TITLE
Post-mortem for empty file in nix store

### ISSUE THREAD

**Issue by domenkozar** [snabblab/snabblab-nixos#42]
Last week we came across an ugly impurity in Nix architecture: our filesystem has failed us and there was a completely empty file in nix store. See https://github.com/NixOS/nixpkgs/issues/15581

The empty file would manifest into something like this (bash is a terrible language):

```
building path(s) '/nix/store/fpsaqgl3slp7cqih9if1ckgxkpsc16z0-initrd'
cp: missing destination file operand after '.'
Try 'cp --help' for more information.
builder for '/nix/store/8wf1gkjm22b9kxfwadvb2d02jsajhi7q-initrd.drv' failed with exit code 1
```

I remedied the issue by running following command twice:

`nixops ssh-for-each -p -d lab-production 'nix-store --verify --check-contents --repair'`

But in future I propose we do two things:

- mount ext4 root partition with `data=journal` as I've already tried in https://github.com/snabblab/snabblab-nixos/commit/89ecf206ca2cd2cf160ae5d8957520a75952b583, but that doesn't work correctly (expressions fails to evalute)

- have a nightly timer that checks nix store integrity (alternative is to always do this, but that has major performance impacts)
 
- document this upstream for future reference as this seriously damaged Nix workings. It happened to me once it corrupted sqlite database and we currently have no other  way of fixing that without rerunning `nixos-install` - which is very easy, but painful

**Comment by domenkozar** [comment]
According to this study https://www.usenix.org/node/186195, this sounds like a good plan.

**Comment by lethalman** [comment]
@domenkozar what plan? As I understood in your comment, `data=journal` is not enough?

**Comment by domenkozar** [comment]
@lethalman Nix expression for some reason doesn't evaluate using that commit, see https://github.com/snabblab/snabblab-nixos/commit/f0f9e89f61d81cc35ff2a6eecbbc31e9c5e30d7c

**Comment by domenkozar** [comment]
The issue persists, no ideas how to explain it yet:

```
[root@lugano-1:/home/domenkozar]# ls -la /nix/store/igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl
-r--r--r-- 1 root root 2294 Jan  1  1970 /nix/store/igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl

[root@lugano-1:/home/domenkozar]# nix-store -r /nix/store/8wf1gkjm22b9kxfwadvb2d02jsajhi7q-initrd.drv
these derivations will be built:
  /nix/store/8wf1gkjm22b9kxfwadvb2d02jsajhi7q-initrd.drv
building path(s) '/nix/store/fpsaqgl3slp7cqih9if1ckgxkpsc16z0-initrd'
cp: missing destination file operand after '.'
Try 'cp --help' for more information.
builder for '/nix/store/8wf1gkjm22b9kxfwadvb2d02jsajhi7q-initrd.drv' failed with exit code 1
error: build of '/nix/store/8wf1gkjm22b9kxfwadvb2d02jsajhi7q-initrd.drv' failed

[root@lugano-1:/home/domenkozar]# ls -la /nix/store/igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl
-r--r--r-- 1 root root 0 May 23 09:32 /nix/store/igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl
```

**Comment by lethalman** [comment]
I think the problem is that `.` in the store path?

**Comment by domenkozar** [comment]
@lethalman where do you see `.` in store path? `cp` fails to copy things since it executes `/nix/store/igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl` and that fails to output anything since it's an empty file.

**Comment by domenkozar** [comment]
I can reproduce this on another server, `lugano-3`. So it must be our configuration.

**Comment by domenkozar** [comment]
Confirmed! It's due to https://github.com/snabblab/snabblab-nixos/blob/master/modules/sudo-in-builds.nix 

If I uncomment that module, initrd builds successfully.

**Comment by domenkozar** [comment]
We desperately need sudo in builds, so I'll try two things:

- bisect what files is causing the issue and see if we can avoid the problem

- implement https://github.com/snabblab/snabblab-nixos/issues/38

**Comment by domenkozar** [comment]
The problem is in `"${config.system.path}"`, for some reason it's mount that file as empty:

`-r--r--r--   1 root      0     0 May 23 10:23 igp3zlizdgjr5zg041c5a5rnp24pimmb-paths-from-graph.pl`

**Comment by domenkozar** [comment]
The fix: https://github.com/domenkozar/nixpkgs/commit/b639fa00d7e1a00b0b760866e9ce6378db2ccf2d

**Comment by domenkozar** [comment]
Successfully verified on my machine that sudo still works.

Successfully verified on lugano-3 that sudo in builds still works while initrd can now build.

Deploying to snabblab in a few moments.

**Comment by domenkozar** [comment]
This is happeninig again with `/etc/pam.d/sudo` which is very inconvenient. The bug will need to be fixed in Nix, we could avoid it by whitelisting chrooted dirs only when needed.

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nix/issues/942 to track this effort upstream.
