### ISSUE TITLE
snabblab "next" branch?

### ISSUE THREAD

**Issue by lukego** [snabblab/snabblab-nixos#73]
Should we create a `next` branch for snabblab? This would contain code that we do want but don't necessarily want to deploy immediately.

I am thinking of maintenance work like 79ec4e5ca80b6863cbccac1f548d267aac3a9d87 that we do want to integrate and merge into a development tree but that we may want to "release" to the Hydra jobsets less frequently in order to keep them stable and avoid rerunning tests unnecessarily.

(Changes that are not expected to cause rebuilds might skip this step and merge directly onto master e.g. updates to the R reports or lab server definitions.)

**Comment by domenkozar** [comment]
+1 to standardize the name to `next` and document it.

**Comment by domenkozar** [comment]
I've created `next` and the performance improvements are already on the way: https://github.com/snabblab/snabblab-nixos/pull/77

I'll document the development process as part of the documentation effort going on currently. Thanks!
