### ISSUE TITLE
Reduce evaluation time of snabb-matrix jobset

### ISSUE THREAD

**Issue by domenkozar** [snabblab/snabblab-nixos#74]
`$ \time nix-instantiate jobsets/snabb-matrix.nix --arg snabbAsrc ~/dev/snabb/snabbswitch --argstr snabbAname master --arg reports '["basic"]' --arg benchmarkNames '["dpdk" "iperf" "basic"]' --show-trace -A benchmarks --arg numTimesRunBenchmark 5`

currently takes ~80s on my laptop. All murren jobsets take up to 1300s.

**Comment by domenkozar** [comment]
Found the issue!

Following patch gets it down to 0.26s:

```
$ git diff
diff --git a/lib/benchmarks.nix b/lib/benchmarks.nix
index a97b374..f0b48ec 100644
--- a/lib/benchmarks.nix
+++ b/lib/benchmarks.nix
@@ -135,7 +135,7 @@ rec {
     in mkSnabbBenchTest {
       name = "iperf_conf=${conf}_snabb=${versionToAttribute snabb.version or ""}_kernel=${versionToAttribute kPackages.kernel.version}_qemu=${versionToAttribute qemu.version}";
       inherit hardware kPackages snabb times qemu;
-      testNixEnv = mkNixTestEnv { inherit kPackages; };
+      testNixEnv = "";
       toCSV = drv: ''
         score=$(awk '/^IPERF-/ { print $2 }' < ${drv}/log.txt)
         ${writeCSV drv "iperf" "Gbps"}
@@ -171,7 +171,8 @@ rec {
       name = "l2fwd_pktsize=${pktsize}_conf=${conf}_snabb=${versionToAttribute snabb.version or ""}_dpdk=${versionToAttribute dpdk.version}_qemu=${versionToAttribute qemu.version}";
       inherit snabb qemu times hardware dpdk kPackages;
       needsNixTestEnv = true;
-      testNixEnv = mkNixTestEnv { inherit kPackages dpdk; };
+      #testNixEnv = mkNixTestEnv { inherit kPackages dpdk; };
+      testNixEnv = "";
       toCSV = drv: ''
         score=$(awk '/^Rate\(Mpps\):/ { print $2 }' < ${drv}/log.txt)
         ${writeCSV drv "l2fwd" "Mpps"}
```

**Comment by domenkozar** [comment]
Turns out it's expensive to evaluate `test_env.nix`. If we could only build one image that would halve the time, but I'll probably end up implementing some LRU cached function arguments logic or similar to mitigate this.

**Comment by lukego** [comment]
Looks like some excellent nix optimization hacking :)

**Comment by domenkozar** [comment]
Fixed in https://github.com/snabblab/snabblab-nixos/commit/2167749c456c503386258bcac351a0f3f3c6eb18

https://hydra.snabb.co/jobset/domenkozar-sandbox/next went from **814s** to **14s**.

**Comment by lukego** [comment]
Great work !!! :fireworks:
