### ISSUE TITLE
Setup Hydra

### ISSUE THREAD

**Issue by domenkozar** [snabblab/snabblab-nixos#8]
For reference:

- https://github.com/mayflower/mf-nixops/blob/eba049a07b8ecdbafdc3b8515bb71898ed43c789/component/hydra.nix
- https://www.youtube.com/watch?v=RXV0Y5Bn-QQ
- https://github.com/peti/hydra-tutorial

**Comment by domenkozar** [comment]
I'm going to start work on this today. cc @lukego

**Comment by lukego** [comment]
Woohoo!!

**Comment by domenkozar** [comment]
It's up and running.
